import { log } from "@ragbag/shared";
import { eq } from "drizzle-orm";
import { db, sql } from "../db/client.js";
import { itemChunk } from "../db/schema.js";
import { env } from "../env.js";
import { chunkText } from "./chunk.js";
import { openai } from "./openai.js";
import { recordUsage } from "./usage.js";

// Stage 4 (plan §7): chunk the extracted text and upsert item_chunk rows.
// The tsvector column is generated by Postgres; embeddings are written when
// OpenAI + pgvector are both available — otherwise chunks alone still power
// server-side keyword search, and embeddings are backfillable later.

let vectorColumnKnown: boolean | undefined;

export async function hasVectorColumn(): Promise<boolean> {
  if (vectorColumnKnown === undefined) {
    const rows = await sql`
      select 1 from information_schema.columns
      where table_name = 'item_chunk' and column_name = 'embedding'`;
    vectorColumnKnown = rows.length > 0;
  }
  return vectorColumnKnown;
}

/**
 * Idempotent self-heal for installs that add pgvector after migrating: the
 * same conditional DDL migration 0002 runs, so the column appears on the
 * next boot. No-op (with a NOTICE) when the extension is still missing.
 */
export async function ensureVectorColumn(): Promise<void> {
  await sql.unsafe(`
    DO $$
    BEGIN
      IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
        ALTER TABLE "item_chunk" ADD COLUMN IF NOT EXISTS "embedding" vector(1536);
        CREATE INDEX IF NOT EXISTS "item_chunk_embedding_idx" ON "item_chunk"
          USING hnsw ("embedding" vector_cosine_ops);
      END IF;
    END
    $$;`);
  vectorColumnKnown = undefined;
}

export async function indexItemText(input: {
  userId: string;
  itemId: string;
  text: string;
  /** Budget gate decided by the pipeline; embeddings are skipped when false. */
  mayEmbed: boolean;
}): Promise<void> {
  const chunks = chunkText(input.text);
  await db.delete(itemChunk).where(eq(itemChunk.itemId, input.itemId));
  if (chunks.length === 0) return;

  await db.insert(itemChunk).values(
    chunks.map((content, idx) => ({
      itemId: input.itemId,
      userId: input.userId,
      idx,
      content,
    })),
  );

  if (!openai || !input.mayEmbed || !(await hasVectorColumn())) return;

  const res = await openai.embeddings.create({ model: env.AI_EMBED_MODEL, input: chunks });
  await recordUsage({
    userId: input.userId,
    itemId: input.itemId,
    kind: "embed",
    model: env.AI_EMBED_MODEL,
    inputTokens: res.usage?.prompt_tokens ?? 0,
    outputTokens: 0,
  });

  // One statement for all chunks: embeddings as '[x,y,...]' literals.
  const vectors = res.data.map((d) => `[${d.embedding.join(",")}]`);
  const indexes = res.data.map((_, i) => i);
  await sql`
    update item_chunk as c
    set embedding = v.emb::vector
    from (select unnest(${vectors}::text[]) as emb, unnest(${indexes}::int[]) as idx) as v
    where c.item_id = ${input.itemId} and c.idx = v.idx`;
  log.debug("embedded item chunks", { itemId: input.itemId, chunks: chunks.length });
}
